### ISSUE TITLE
Update wiki links & request to link it on Damage page

### ISSUE THREAD

**Issue by Surxe** [DustinRepo/DnDUtilWeb#1]
Hey! Spells & Gun's wiki team here! Would you be willing to have this linked on the Damage page? We updated some of the sections in the damage page so a few links from the "?" icons are out of date, like Added Weapon Damage. Thanks in advance!

**Comment by DustinRepo** [comment]
damn I missed this for a long time but done lmao

**Comment by Surxe** [comment]
> damn I missed this for a long time but done lmao

Np haha, thanks!
